export function renderSkillsPage({ catalog, version }) {
  const safeCatalog = JSON.stringify(catalog).replace(/</g, "\\u003c");
  return String.raw`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Skills · MundusX Chat</title>
  <style>
    :root{color-scheme:light dark;--bg:#f5f7ff;--panel:#fff;--text:#151827;--muted:#687087;--line:#dfe3f0;--accent:#596cff;--soft:#eef1ff;--ok:#0b9668;--warn:#b66b00}
    @media(prefers-color-scheme:dark){:root{--bg:#080b17;--panel:#11162a;--text:#f5f6ff;--muted:#aab2c8;--line:#29314d;--accent:#7b7cff;--soft:#181e39;--ok:#55d6a7;--warn:#f0b35b}}
    *{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.5 Inter,Segoe UI,sans-serif}button,select,textarea{font:inherit}header{height:64px;display:flex;align-items:center;justify-content:space-between;padding:0 24px;border-bottom:1px solid var(--line);background:color-mix(in srgb,var(--panel) 88%,transparent);position:sticky;top:0;z-index:2}header a{color:var(--accent);text-decoration:none;font-weight:700}.layout{width:min(1180px,calc(100% - 32px));margin:28px auto;display:grid;grid-template-columns:320px minmax(0,1fr);gap:20px}.panel{border:1px solid var(--line);border-radius:16px;background:var(--panel);box-shadow:0 14px 45px rgba(25,30,70,.08)}.sidebar{padding:14px}.intro{padding:18px;border-bottom:1px solid var(--line)}h1,h2,p{margin:0}.intro p,.muted{color:var(--muted)}.skills{display:grid;gap:6px;padding-top:10px}.skill{width:100%;border:1px solid transparent;border-radius:10px;padding:10px;text-align:left;color:var(--text);background:transparent;cursor:pointer}.skill:hover,.skill.active{border-color:var(--line);background:var(--soft)}.skill strong,.skill small{display:block}.skill small{color:var(--muted);margin-top:2px}.badge{display:inline-flex;margin-top:6px;padding:2px 7px;border-radius:999px;background:var(--soft);color:var(--muted);font-size:11px}.editor{padding:22px;display:grid;gap:16px}.notice{padding:12px 14px;border:1px solid color-mix(in srgb,var(--warn) 35%,var(--line));border-radius:10px;background:color-mix(in srgb,var(--warn) 8%,var(--panel));color:var(--muted)}label{display:grid;gap:7px;font-weight:700}textarea{width:100%;min-height:270px;resize:vertical;border:1px solid var(--line);border-radius:11px;padding:13px;color:var(--text);background:var(--bg);font-family:Consolas,monospace;font-size:13px}.meta{display:grid;grid-template-columns:1fr auto;gap:12px;align-items:start}.path{font-family:Consolas,monospace;color:var(--accent);overflow-wrap:anywhere}.actions{display:flex;gap:9px;flex-wrap:wrap}.actions button{border:1px solid var(--line);border-radius:9px;padding:9px 13px;color:var(--text);background:var(--panel);cursor:pointer}.actions .primary{border-color:transparent;color:#fff;background:var(--accent)}.preview{min-height:90px;padding:13px;border:1px solid var(--line);border-radius:10px;background:var(--soft);white-space:pre-wrap}.status{font-weight:700}.status.ok{color:var(--ok)}.status.warn{color:var(--warn)}@media(max-width:760px){.layout{grid-template-columns:1fr}.meta{grid-template-columns:1fr}header{padding:0 16px}}
  </style>
</head>
<body>
  <header><strong>MundusX Chat · Skills</strong><a href="/">Back to Chat</a></header>
  <main class="layout">
    <section class="panel sidebar"><div class="intro"><h1>Runtime skills</h1><p>Registry v${Number(version) || 1}. Select a skill to prepare and validate a local draft.</p></div><div class="skills" id="skills"></div></section>
    <section class="panel editor">
      <div class="meta"><div><h2 id="title">Select a skill</h2><p class="muted" id="description"></p></div><span class="badge" id="enabled"></span></div>
      <div class="notice"><strong>Publishing is intentionally unavailable.</strong> Without authentication, this page cannot read or rewrite global skill instructions. Drafts stay only in this browser; repository review and deployment remain the publishing path.</div>
      <div><div class="muted">Runtime file</div><div class="path" id="path">apps/chat/skills/</div></div>
      <label>Proposed Markdown<textarea id="draft" placeholder="# Skill title&#10;&#10;Purpose: ...&#10;&#10;Rules:&#10;- ..."></textarea></label>
      <div class="actions"><button class="primary" id="save" type="button">Save local draft</button><button id="clear" type="button">Clear draft</button><button id="copy" type="button">Copy prompt preview</button></div>
      <div><div class="status" id="status">Choose a skill to begin.</div><div class="muted" id="details"></div></div>
      <div><strong>Prompt preview</strong><div class="preview" id="preview">The first 12 meaningful instruction lines will appear here.</div></div>
    </section>
  </main>
  <script>
    const catalog=${safeCatalog};let active=null;const skills=document.getElementById('skills');const draft=document.getElementById('draft');
    function key(){return active?'mundusx.skillDraft.v1.'+active.id:''}function meaningful(value){return String(value||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).filter(x=>!x.startsWith('#')).map(x=>x.replace(/^[-*]\s+/,'' )).map(x=>x.replace(/^(?:Purpose|Rules|Facts|Examples|Output|Do|Do not)\s*:\s*/i,'')).filter(Boolean)}
    function validate(){const value=draft.value.trim(),errors=[],warnings=[];if(!value)errors.push('Skill Markdown is required');if(value.length>12000)errors.push('Skill Markdown exceeds 12000 characters');const first=value.split(/\r?\n/).find(x=>x.trim());if(value&&!first.trim().startsWith('#'))errors.push('The first meaningful line must be a Markdown heading');if(/-----BEGIN [A-Z0-9 ]*PRIVATE KEY-----|\b(?:api[_-]?key|access[_-]?token|client[_-]?secret|password)\s*[:=]/i.test(value))errors.push('Credentials and private keys are not allowed');const lines=meaningful(value);if(lines.length>12)warnings.push('Only the first 12 meaningful instruction lines enter the model prompt');document.getElementById('preview').textContent=lines.slice(0,12).join(' ')||'The first 12 meaningful instruction lines will appear here.';const status=document.getElementById('status'),details=document.getElementById('details');status.className='status '+(errors.length?'warn':'ok');status.textContent=errors.length?'Draft needs attention':warnings.length?'Draft is valid with a warning':'Draft is valid';details.textContent=[...errors,...warnings].join(' · ')}
    function select(entry,button){active=entry;document.querySelectorAll('.skill').forEach(x=>x.classList.remove('active'));button.classList.add('active');document.getElementById('title').textContent=entry.title;document.getElementById('description').textContent=entry.description;document.getElementById('enabled').textContent=entry.enabled?'Enabled':'Disabled';document.getElementById('path').textContent='apps/chat/skills/'+entry.file;draft.value=localStorage.getItem(key())||'';validate()}
    catalog.forEach((entry,index)=>{const button=document.createElement('button');button.className='skill';button.type='button';button.innerHTML='<strong></strong><small></small><span class="badge"></span>';button.querySelector('strong').textContent=entry.title;button.querySelector('small').textContent=entry.description;button.querySelector('.badge').textContent=entry.enabled?'Enabled':'Disabled';button.addEventListener('click',()=>select(entry,button));skills.appendChild(button);if(index===0)select(entry,button)});
    draft.addEventListener('input',validate);document.getElementById('save').addEventListener('click',()=>{if(!active)return;localStorage.setItem(key(),draft.value);validate();document.getElementById('details').textContent='Draft saved only in this browser. '+document.getElementById('details').textContent});document.getElementById('clear').addEventListener('click',()=>{if(!active)return;localStorage.removeItem(key());draft.value='';validate()});document.getElementById('copy').addEventListener('click',async()=>{await navigator.clipboard.writeText(document.getElementById('preview').textContent)});
  </script>
</body></html>`;
}
